### ISSUE TITLE
你好，请教一下电子班牌的问题，UI应该怎么给图呢？

### ISSUE THREAD

**Issue by AbrahamCaiJin** [bifan-wei/BeehiveContent#1]
大佬，你好，能请教一下电子班牌的问题吗？这两天我们要做这个，我想请问一下这个UI一般给多大的图？还是按照手机一样给，急求，谢谢

**Comment by bifan-wei** [comment]
兄die你是不是评论错地方了？

**Comment by daochushilang** [comment]
额，不好意思，我是csdn的博文上看到的关于电子班牌的，想请教一下，这个链接是博主上面，我以为是博主GitHub

**Comment by AbrahamCaiJin** [comment]
> 兄die你是不是评论错地方了？

额，不好意思，我是csdn的博文上看到的关于电子班牌的，想请教一下，这个链接是博主上面，我以为是博主GitHub
